# Generated by Django 3.1.5 on 2021-08-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_post_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.NullBooleanField(default=True),
        ),
    ]
