# Generated by Django 3.1.5 on 2021-09-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210906_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='judul',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
