# Generated by Django 3.1.5 on 2021-09-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
