# Generated by Django 3.1.5 on 2021-09-10 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabang', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdtk', models.CharField(max_length=10, null=True, unique=True)),
                ('nama_toko', models.CharField(max_length=200, null=True)),
                ('ip', models.CharField(max_length=100, null=True)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toko.cabang')),
            ],
        ),
    ]
