# Generated by Django 3.2.4 on 2021-09-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passsql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=10, unique=True)),
                ('bln', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
