# Generated by Django 3.2.4 on 2021-09-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0002_passsql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passsql',
            name='bln',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='passsql',
            name='password',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
